### ISSUE TITLE
Blosc decompression error at compression level 0

### ISSUE THREAD

**Issue by marklam** [Apollo3zehn/PureHDF#74]
Doesn't happen with the default compression level (at least on this chunk configuration).

I've created a branch with a repro case in it in case it's specific to the chunk sizes or data type etc.

https://github.com/marklam/Roundtrip3DArrayOfStructList/tree/blosc

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 272
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs:line 56
   at PureHDF.VOL.Native.NativeDataset.Read[T](Selection fileSelection, Selection memorySelection, UInt64[] memoryDims, H5DatasetAccess datasetAccess) in /home/runner/work/PureHDF/PureHDF/src/PureHDF/VOL/Native/API.Reading/NativeDataset.cs:line 203
   at PureHDF.VOL.Native.NativeDataset.Read[T](Selection fileSelection, Selection memorySelection, UInt64[] memoryDims) in /home/runner/work/PureHDF/PureHDF/src/PureHDF/VOL/Native/API.Reading/NativeDataset.cs:line 161
   at Program.initializer@1-4(Int32 i, Int32 j) in C:\Users\markl\source\repos\ConsolePureHDFroundtrip\ConsolePureHDFroundtrip\Program.fs:line 95
   at Program.initializer@1-3(Int32 i) in C:\Users\markl\source\repos\ConsolePureHDFroundtrip\ConsolePureHDFroundtrip\Program.fs:line 90
   at <StartupCode$ConsolePureHDFroundtrip>.$Program.main@() in C:\Users\markl\source\repos\ConsolePureHDFroundtrip\ConsolePureHDFroundtrip\Program.fs:line 87

  This exception was originally thrown at this call stack:
    PureHDF.Filters.Blosc2Filter.Filter(PureHDF.Filters.FilterInfo) in Blosc2Filter.cs
    PureHDF.Filters.H5Filter.ExecutePipeline(PureHDF.VOL.Native.FilterDescription[], uint, PureHDF.Filters.H5FilterFlags, int, System.Memory<byte>) in H5Filter.cs

Inner Exception 1:
Exception: Filter pipeline failed.

Inner Exception 2:
Exception: Blosc decompression error.
```

**Comment by Apollo3zehn** [comment]
Thank you, I`ll try to investigate this and your other issue today evening

**Comment by Apollo3zehn** [comment]
It should work now with version `1.0.0-beta.12` (for both dependencies, `PureHDF` and `PureHDF.Filters.Blosc2`) :-)

There were two bugs:

- I had another issue logged (#68), wondering why the file size is not reduced when using Blosc. The reason was that the Blosc target buffer has the size of a single chunk and before it is returned, it should be sliced to the actual compressed size. But that was not the case and so the data has been compressed but the buffer size never changed.

- The problem you encountered was due to the fact that with compression level 0, no compression takes place. But that does not mean that a buffer of the size of a single chunk is large enough. Actually, Blosc adds an overhead of 32 bytes to the uncompressed data which `PureHDF.Filters.Blosc2` did not account for and so Blosc was complaining. Now the target buffer for compression is always 32 bytes larger than the source buffer.

**Comment by marklam** [comment]
Thanks, that no longer crashes.
